issue1/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.issue_home, name='issue_home'),
	path('delete/<list_id>', views.delete, name='delete'),
	path('cross_off/<list_id>', views.cross_off, name='cross_off'),
	path('uncross/<list_id>', views.uncross, name='uncross'),
	path('edit/<list_id>', views.edit, name='edit'),
	path('addnew/', views.addnew, name='addnew'), 
	path('detail/<list_id>', views.detail, name='issuedetail'),
]
    

mysite/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authenticate.urls')),
    path('todo/', include('todo_list.urls')),
    path('programs/', include('programs.urls')),
    path('messages/', include('chat.urls')),
    path('issue1/', include('issue1.urls')),
]

chat/models.py
from django.db import models
from django.conf import settings
from django.db import models
from django.db.models import Q

class ThreadManager(models.Manager):
    """
    This class is responsible for managing the threads that are created
    and implements lookups of those threads
    """

    def by_user(self, user):
        """
        Not sure what this method does

        :param user:
        :return:
        """

        # TODO: Rename variables to be easier to understand

        qlookup = Q(first=user) | Q(second=user)

        qlookup2 = Q(first=user) & Q(second=user)

        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()

        return qs



    def get_or_new(self, user, other_username):
        """
        Not sure what this method does

        My assumption is that it gets a new thread for the users

        :param user:
        :param other_username:
        :return:
        """

        username = user.username

        if username == other_username:

            return None

        qlookup1 = Q(first__username=username) & Q(second__username=other_username)

        qlookup2 = Q(first__username=other_username) & Q(second__username=username)

        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()

        if qs.count() == 1:

            return qs.first(), False

        elif qs.count() > 1:

            return qs.order_by('timestamp').first(), False

        else:

            Klass = user.__class__

            user2 = Klass.objects.get(username=other_username)

            if user != user2:

                obj = self.model(

                        first=user, 

                        second=user2

                    )

                obj.save()

                return obj, True

            return None, False


class Thread(models.Model):
    """
    This class initializes the thread and ForeignKey
    of the first and second chat thread. It also holds the value for the timestamp
    """

    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')

    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')

    updated      = models.DateTimeField(auto_now=True)

    timestamp    = models.DateTimeField(auto_now_add=True)

    

    objects      = ThreadManager()


    # TODO What does this property decorator do?

    @property

    def room_group_name(self):
        """
        This method is a room_group_name getter method

        :return:
        """

        return f'chat_{self.id}'



    def broadcast(self, msg=None):
        """
        This method broadcasts the message of the user
        to the room group name

        :param msg:
        :return:
        """

        if msg is not None:

            #TODO: I think this is defaulting to admin user, this method doesn't take in user how does that get overrode

            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')

            return True

        return False





class ChatMessage(models.Model):
    """
    This class initializes the chat message, user and thread
    of the first and second chat thread. It also holds the value for the timestamp
    """

    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)

    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)

    message     = models.TextField()

    timestamp   = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):

    message = forms.CharField(

            widget=forms.TextInput(

                attrs={"class": "form-control"}

                )
            )

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import Http404, HttpResponseForbidden

from django.shortcuts import render

from django.urls import reverse

from django.views.generic.edit import FormMixin
from django.views.generic import DetailView, ListView
from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    """
    This class creates an inbox view using the inbox template
    """

    template_name = 'chat/inbox.html'

    def get_queryset(self):
        """
        This is a getter for the thread object

        :return:
        """

        return Thread.objects.by_user(self.request.user)

class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    """
    This class defines the thread view
    """

    template_name = 'chat/thread.html'

    form_class = ComposeForm

    success_url = './'

    #TODO: I believe this method could be inheritied as it's repeated above

    def get_queryset(self):

        return Thread.objects.by_user(self.request.user)



    def get_object(self):
        """
        This method is a getter for the thread between two users to use
        If this fails the web server will 404 Resource not found

        :return:
        """

        other_username  = self.kwargs.get("username")

        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)

        if obj == None:

            raise Http404

        return obj



    def get_context_data(self, **kwargs):
        """
        This method is a recursive function that gets the form details
        and returns the content of the form

        :param kwargs:
        :return:
        """

        # TODO: I don't fully understand this method

        context = super().get_context_data(**kwargs)

        context['form'] = self.get_form()

        return context



    def post(self, request, *args, **kwargs):
        """
        This method checks if the user is authenticated and then calls the POST to get the form information.
        After this it checks if the form is valid and then returns the form.

        :param request:
        :param args:
        :param kwargs:
        :return:
        """

        if not request.user.is_authenticated:

            return HttpResponseForbidden()

        self.object = self.get_object()

        form = self.get_form()

        if form.is_valid():

            return self.form_valid(form)

        else:

            return self.form_invalid(form)



    def form_valid(self, form):
        """
        This method sets the thread user and message from the form data and creates the chat object

        :param form:
        :return:
        """

        thread = self.get_object()

        user = self.request.user

        message = form.cleaned_data.get("message")

        ChatMessage.objects.create(user=user, thread=thread, message=message)

        return super().form_valid(form)

chat/templates/chat/thread.html
{% extends "authenticate/base.html" %}

{% load static %}

{% block content %}

<div class="container">
	<h3 class="subhead">Chat with
		{% if user != object.first %}{{ object.first }}
		{% else %}{{ object.second }}
		{% endif %}
	</h3>
<div class="row" style=" margin-left: 30px; height:350px">
	<div
		class="col-md-8" id="roll" 
		style="border-left: 3px rgb(41, 41, 95) solid; overflow-y:scroll; height: 300px; ">
		<ul id='chat-items' style="text-align: left">

			{% for chat in object.chatmessage_set.all %}

				<li>
					<font size="2">
						<b>
							{{ chat.user }}</b>
						says:</font>

					<br/>
					{{ chat.message }}
				</li>
				<br/><br/>
			{% endfor %}

		</ul>
	</div>
	<div class="col-md-3" style="border-left:3px rgb(41, 41, 95) solid; height: 300px">
		<table>
			<th>
				<p>members</p>
			</th>
			<td></td>
		</table>
	</div>
</div>



<form id='form' method='POST'> {% csrf_token %}
	<input type='hidden' id='myUsername' value='{{ user.username }}' />

{{form.as_p }}

<input type='submit' class="btn btn-secondary" style="width:170px; background-color: rgb(41, 41, 95); color:rgb(157, 196, 253)">

</form>

</div>

{% endblock %}



{% block script %}

<script src="{% static 'reconnecting-websocket.js' %}"></script>

<script>
//console.log(window.location)
var loc=window.location
var formData = $("#form")
var msgInput = $("#id_message")
var chatHolder = $("#chat-items")
var me = $("#myUsername").val()

var wsStart = 'ws://' 

if (loc.protocol == 'https:'){
	wsStart = 'wss://'
}
var endpoint = wsStart + loc.host + loc.pathname
var socket = new ReconnectingWebSocket(endpoint)

socket.onmessage = function(e){
	console.log("message", e)
	var chatDataMsg = JSON.parse(e.data)
	chatHolder.append("<li>"+ chatDataMsg.message + " via " + chatDataMsg.username + "</li>")
}
socket.onopen = function(e){
	console.log("open", e)
	formData.submit(function(event){
		event.preventDefault()
		var msgText = msgInput.val()
		//chatHolder.append("<li>" + msgText + " via " + me + "</li>")
		//var formDataSerialized = formData.serialize()
		var finalData={
			'message':msgText
		}

		socket.send(JSON.stringify(finalData))
		//msgInput.val('')
		formData[0].reset()
	})
}
socket.onerror = function(e){
	console.log("error", e)
}
socket.onclose = function(e){
	console.log("close", e)
}

</script>

{% endblock %}